# Generated by Django 5.0.1 on 2024-01-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('mail', models.CharField(max_length=40, verbose_name='Почта')),
                ('message', models.CharField(max_length=200, verbose_name='Комментарий')),
            ],
        ),
    ]
