# Generated by Django 5.1.4 on 2025-01-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('delivery_address', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactsForm',
        ),
    ]
