# Generated by Django 5.1.4 on 2025-01-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_application', '0002_profile_delete_contactsform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='passwd',
            new_name='password',
        ),
    ]
