# Generated by Django 5.1.4 on 2025-01-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_application', '0003_rename_passwd_profile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
                ('img_ref', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('profile_id', models.IntegerField()),
                ('in_cart', models.BooleanField(default=False)),
            ],
        ),
    ]
