# Generated by Django 5.1.4 on 2025-01-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_application', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profile_id',
            field=models.IntegerField(default=0),
        ),
    ]
