# Generated by Django 5.1.4 on 2025-01-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_application', '0005_alter_product_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
