# Generated by Django 5.0.1 on 2024-02-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='selected',
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.FileField(upload_to='image', verbose_name='category_photo'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.FileField(upload_to='image', verbose_name='dish_photo'),
        ),
    ]
