# Generated by Django 5.0.1 on 2024-02-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_category_selected_alter_category_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='order',
            new_name='for_an_order',
        ),
        migrations.AddField(
            model_name='dish',
            name='in_order_list',
            field=models.BooleanField(default=False),
        ),
    ]
