# Generated by Django 5.0.1 on 2024-02-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_order_dish_for_an_order_dish_in_order_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
