# Generated by Django 5.0 on 2024-01-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='default', max_length=50)),
                ('pen_color', models.CharField(default='#000000', max_length=7)),
                ('bg_color', models.CharField(default='#ffffff', max_length=7)),
                ('img', models.FileField(upload_to='')),
                ('pen_width', models.IntegerField(default=1)),
            ],
        ),
    ]
