# Generated by Django 5.0 on 2024-01-13 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_canvasmodel_bg_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canvasmodel',
            name='img',
        ),
    ]
